In [1]:
import pandas as pd
import numpy as np

# Apply function to every row in a Pandas DataFrame

In [3]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [5]:
# Using vectorized operations
df["add"] = df['A'] + df['B'] + df['C']
print(df["add"])

0    12
1    15
2    18
Name: add, dtype: int64

In [6]:
df

   A  B  C  add
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18

In [ ]:
# Using .values() axis=1 is for rows
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df['add'] = np.sum(df[['A','B','C']].values , axis=1)
print(df)

   A  B  C  add
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18

In [10]:
# Using itertuples()
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
res = []
for row in df.itertuples(index=False):
    res.append(row.A + row.B + row.C)
df['add'] = res
print(df)

   A  B  C  add
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18

In [11]:
# Using list comprehension
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df['add'] = [a + b + c for a, b, c in zip(df['A'], df['B'], df['C'])]
print(df)

   A  B  C  add
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18