In [1]:
import numpy as np
import pandas as pd

# Adding New Column to Existing DataFrame in Pandas
There are 5 different ways to do it which are as follows :

- By Declaring a New List as column
- By using DataFrame.assign() method
- By using Dictionary
- By using DataFrame.insert()
- By using Dataframe.loc()

### By Declaring a New List as column

In [4]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}

df = pd.DataFrame(data)
address = ['NewYork', 'Chicago', 'Boston', 'Miami']
df['Address'] = address
df

     Name  Height Qualification  Address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D    Miami

### By using DataFrame.assign() method

In [5]:
df = df.assign(address = ['Mumbai', 'Delhi', 'Chenai', 'Hyd'])
df

     Name  Height Qualification  Address address
0  Pandas       1             A  NewYork  Mumbai
1   Geeks       2             B  Chicago   Delhi
2     for       3             C   Boston  Chenai
3   Geeks       4             D    Miami     Hyd

### By using Dictionary

In [7]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}

df = pd.DataFrame(data)

address = {'Pandas': 'NewYork', 'Geeks': 'Chicago', 
            'for': 'Boston', 'Geeks_2': 'Miami'}
df

     Name  Height Qualification
0  Pandas       1             A
1   Geeks       2             B
2     for       3             C
3   Geeks       4             D

In [9]:
# Method -1
df['Address'] = df['Name'].map(address)
df

     Name  Height Qualification  Address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D  Chicago

In [10]:
# Method-2
new_columns = {'Age': [21, 22, 23, 24], 
               'City': ['NY', 'LA', 'SF', 'DC']}

df = df.assign(**new_columns)
df

     Name  Height Qualification  Address  Age City
0  Pandas       1             A  NewYork   21   NY
1   Geeks       2             B  Chicago   22   LA
2     for       3             C   Boston   23   SF
3   Geeks       4             D  Chicago   24   DC

### By using DataFrame.insert()

In [17]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}

df = pd.DataFrame(data)

df.insert(2,"Age",[21,22,22,12],True)
df

     Name  Height  Age Qualification
0  Pandas       1   21             A
1   Geeks       2   22             B
2     for       3   22             C
3   Geeks       4   12             D

### By using Dataframe.loc()

In [19]:
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}

df = pd.DataFrame(data)
df.loc[df['Height'] >=3, 'Category'] = 'Tall'
df.loc[df['Height'] <3, 'Category'] = 'Short'
df

     Name  Height Qualification Category
0  Pandas       1             A    Short
1   Geeks       2             B    Short
2     for       3             C     Tall
3   Geeks       4             D     Tall