In [1]:
import numpy as np
import pandas as pd

# Pandas DataFrame drop() Method Syntax
## `DataFrame.drop()`

### Syntax

```python
DataFrame.drop(
    labels=None,
    axis=0,
    index=None,
    columns=None,
    level=None,
    inplace=False,
    errors='raise'
)

| Parameter | Description |
| --- | --- |
| **`labels`** | String or list of strings referring to row or column names. |
| **`axis`** | `0` or `'index'` → Rows; `1` or `'columns'` → Columns. |
| **`index`** | Single label or list of labels referring to rows. Alternative to `axis=0`. |
| **`columns`** | Single label or list of labels referring to columns. Alternative to `axis=1`. |
| **`level`** | Specifies the level when the DataFrame has a multi-level index. |
| **`inplace`** | If `True`, modifies the original DataFrame. |
| **`errors`** | `'raise'` → raises an error if a label doesn't exist; `'ignore'` → ignores missing labels and drops the remaining values. |

### Dropping Rows in Pandas by Index Label

In [2]:
df = pd.read_csv('nba.csv' , index_col='Name')
df

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...
Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.drop(['John Holland' , 'R.J. Hunter' , 'Raul Neto'] , inplace=True)
df

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
...,...,...,...,...,...,...,...,...
Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Dropping Columns in Pandas with Column Name

In [4]:
df.drop(['Position' , 'Number'] , axis=1 , inplace=True)
df

                         Team   Age Height  Weight    College      Salary
Name
Avery Bradley  Boston Celtics  25.0    6-2   180.0      Texas   7730337.0
Jae Crowder    Boston Celtics  25.0    6-6   235.0  Marquette   6796117.0
Jonas Jerebko  Boston Celtics  29.0   6-10   231.0        NaN   5000000.0
Amir Johnson   Boston Celtics  29.0    6-9   240.0        NaN  12000000.0
Jordan Mickey  Boston Celtics  21.0    6-8   235.0        LSU   1170960.0
...                       ...   ...    ...     ...        ...         ...
Trey Lyles          Utah Jazz  20.0   6-10   234.0   Kentucky   2239800.0
Shelvin Mack        Utah Jazz  26.0    6-3   203.0     Butler   2433333.0
Tibor Pleiss        Utah Jazz  26.0    7-3   256.0        NaN   2900000.0
Jeff Withey         Utah Jazz  26.0    7-0   231.0     Kansas    947276.0
NaN                       NaN   NaN    NaN     NaN        NaN         NaN

[455 rows x 6 columns]