In [1]:
import numpy as np
import pandas as pd

# Pandas GroupBy
The groupby() function in Pandas is important for data analysis as it allows us to group data by one or more categories and then apply different functions to those groups. This technique is used for handling large datasets efficiently and performing operations like aggregation, transformation and filtration on grouped data.

## Step 1: Splitting Data into Groups

In [8]:
# 1. Group data by a single key
data1 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi',
                 'Gaurav', 'Anuj', 'Princi', 'Abhi'],
        'Age':[27, 24, 22, 32,
               33, 36, 27, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                   'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                         'B.Tech', 'B.com', 'Msc', 'MA']}
df = pd.DataFrame(data1)
print(df)
print(df.groupby('Name').groups)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1    Anuj   24     Kanpur            MA
2     Jai   22  Allahabad           MCA
3  Princi   32    Kannuaj           Phd
4  Gaurav   33    Jaunpur        B.Tech
5    Anuj   36     Kanpur         B.com
6  Princi   27  Allahabad           Msc
7    Abhi   32    Aligarh            MA
{'Abhi': [7], 'Anuj': [1, 5], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}

In [6]:
gk = df.groupby('Name') 
gk.first()

        Age  Address Qualification
Name
Abhi     32  Aligarh            MA
Anuj     24   Kanpur            MA
Gaurav   33  Jaunpur        B.Tech
Jai      27   Nagpur           Msc
Princi   32  Kannuaj           Phd

In [9]:
# 2. Grouping data with multiple keys
a = df.groupby(['Name','Qualification'])
print(a.groups)

{('Abhi', 'MA'): [7], ('Anuj', 'B.com'): [5], ('Anuj', 'MA'): [1], ('Gaurav', 'B.Tech'): [4], ('Jai', 'MCA'): [2], ('Jai', 'Msc'): [0], ('Princi', 'Msc'): [6], ('Princi', 'Phd'): [3]}

In [ ]:
# 3. Grouping data by sorting keys: Group keys are sorted by default using the groupby operation.
df.groupby('Name')['Age'].sum()

Name
Abhi      32
Anuj      60
Gaurav    33
Jai       49
Princi    59
Name: Age, dtype: int64

In [11]:
# 4. Grouping data with object attributes Grouping data with object attributes in Pandas allows us to treat the groups 
# attribute as a dictionary where the keys are unique group values
#  and values are the indices (row labels) corresponding to each group.
df.groupby('Name').groups

{'Abhi': [7], 'Anuj': [1, 5], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}

In [ ]:
# 5. Iterating through groups
grp = df.groupby('Name')
for name, group in grp:
    print(name)
    print(group)
    print()

Abhi
   Name  Age  Address Qualification
7  Abhi   32  Aligarh            MA

Anuj
   Name  Age Address Qualification
1  Anuj   24  Kanpur            MA
5  Anuj   36  Kanpur         B.com

Gaurav
     Name  Age  Address Qualification
4  Gaurav   33  Jaunpur        B.Tech

Jai
  Name  Age    Address Qualification
0  Jai   27     Nagpur           Msc
2  Jai   22  Allahabad           MCA

Princi
     Name  Age    Address Qualification
3  Princi   32    Kannuaj           Phd
6  Princi   27  Allahabad           Msc

In [14]:
# 6. Selecting a group
grp = df.groupby('Name')
grp.get_group('Jai')

  Name  Age    Address Qualification
0  Jai   27     Nagpur           Msc
2  Jai   22  Allahabad           MCA

In [15]:
grp = df.groupby(['Name', 'Qualification'])
grp.get_group(('Jai', 'Msc'))

  Name  Age Address Qualification
0  Jai   27  Nagpur           Msc

## Step 2: Applying Functions to Groups

#### 1. Aggregation:

In [16]:
grp1 = df.groupby('Name')
grp1['Age'].aggregate(np.sum)

/var/folders/1l/9v47gts15g94hr7bhzd03p1w0000gn/T/ipykernel_5271/4113814000.py:2: FutureWarning: The provided callable <function sum at 0x114095440> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['Age'].aggregate(np.sum)

Name
Abhi      32
Anuj      60
Gaurav    33
Jai       49
Princi    59
Name: Age, dtype: int64

In [17]:
grp1 = df.groupby(['Name', 'Qualification'])
grp1['Age'].aggregate(np.sum)

/var/folders/1l/9v47gts15g94hr7bhzd03p1w0000gn/T/ipykernel_5271/1932127849.py:2: FutureWarning: The provided callable <function sum at 0x114095440> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['Age'].aggregate(np.sum)

Name    Qualification
Abhi    MA               32
Anuj    B.com            36
        MA               24
Gaurav  B.Tech           33
Jai     MCA              22
        Msc              27
Princi  Msc              27
        Phd              32
Name: Age, dtype: int64

In [18]:
grp = df.groupby('Name')
grp['Age'].agg([np.sum, np.mean, np.std])

/var/folders/1l/9v47gts15g94hr7bhzd03p1w0000gn/T/ipykernel_5271/3832254242.py:2: FutureWarning: The provided callable <function sum at 0x114095440> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])
/var/folders/1l/9v47gts15g94hr7bhzd03p1w0000gn/T/ipykernel_5271/3832254242.py:2: FutureWarning: The provided callable <function mean at 0x114096840> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])
/var/folders/1l/9v47gts15g94hr7bhzd03p1w0000gn/T/ipykernel_5271/3832254242.py:2: FutureWarning: The provided callable <function std at 0x114096980> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])

        sum  mean       std
Name
Abhi     32  32.0       NaN
Anuj     60  30.0  8.485281
Gaurav   33  33.0       NaN
Jai      49  24.5  3.535534
Princi   59  29.5  3.535534

#### 2. Transformation:

In [20]:
data2 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi', 
                 'Gaurav', 'Anuj', 'Princi', 'Abhi'], 
        'Age':[27, 24, 22, 32, 
               33, 36, 27, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                   'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                         'B.Tech', 'B.com', 'Msc', 'MA'],
        'Score':[23, 34, 35, 45, 47, 50, 52, 53]} 
        
df2 = pd.DataFrame(data2)
grp2 = df2.groupby('Name')
sc = lambda x: (x - x.mean()) / x.std() 
grp2['Score'].transform(sc)

0   -0.707107
1   -0.707107
2    0.707107
3   -0.707107
4         NaN
5    0.707107
6    0.707107
7         NaN
Name: Score, dtype: float64

#### 3. Filtration:

In [21]:
grp2 = df2.groupby('Name')
grp2.filter(lambda x: len(x) >= 2)

     Name  Age    Address Qualification  Score
0     Jai   27     Nagpur           Msc     23
1    Anuj   24     Kanpur            MA     34
2     Jai   22  Allahabad           MCA     35
3  Princi   32    Kannuaj           Phd     45
5    Anuj   36     Kanpur         B.com     50
6  Princi   27  Allahabad           Msc     52

## Step 3: Combining Results

In [22]:
df.groupby('Name').agg({'Age': 'sum'})

        Age
Name
Abhi     32
Anuj     60
Gaurav   33
Jai      49
Princi   59