In [1]:
import numpy as np
import pandas as pd

# Dealing with Rows and Columns in Pandas DataFrame

In [2]:
df = pd.read_csv("nba.csv")
print(df.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

In [4]:
print(df[['Name' , 'Age']])

              Name   Age
0    Avery Bradley  25.0
1      Jae Crowder  25.0
2     John Holland  27.0
3      R.J. Hunter  22.0
4    Jonas Jerebko  29.0
..             ...   ...
453   Shelvin Mack  26.0
454      Raul Neto  24.0
455   Tibor Pleiss  26.0
456    Jeff Withey  26.0
457            NaN   NaN

[458 rows x 2 columns]

### Adding Columns
New columns can be added by assigning a list or series to a column name.

In [5]:
df['Experience'] = 1

In [6]:
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,1
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,1
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,1
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,1
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,1
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,1
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,1
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,1
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

### Deleting Columns
You can delete a column from the DataFrame using the drop() method.

In [7]:
df.drop('Experience' , axis=1 , inplace=True)

In [8]:
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Dealing with Rows

### Selecting Rows
Rows can be selected using .loc[] by row label or index.

In [11]:
data = pd.read_csv("nba.csv", index_col="Name")

first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]

print(first, "\n\n", second)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

 Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

### Adding Rows
New rows can be added using pd.concat().

In [12]:
new_row = {
    'Name': 'Geeks',
    'Team': 'Boston',
    'Number': 3,
    'Position': 'PG',
    'Age': 33,
    'Height': '6-2',
    'Weight': 189,
    'College': 'MIT',
    'Salary': 99999
}

In [14]:
df = pd.concat([df,pd.DataFrame([new_row])] , ignore_index=True)
df.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458,Geeks,Boston,3.0,PG,33.0,6-2,189.0,MIT,99999.0
459,Geeks,Boston,3.0,PG,33.0,6-2,189.0,MIT,99999.0

### Deleting Rows
Rows can be removed using drop() with row labels.

In [23]:
data = pd.read_csv("nba.csv", index_col="Name")
data.drop(["Avery Bradley", "John Holland", "R.J. Hunter"], inplace=True)