In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('nba.csv' ,index_col='Name')
df

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...
Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Examples of Extracting rows using .loc[]

### 1. Multiple parameters

In [5]:
rows = df.loc[['Jae Crowder' , 'Raul Neto']]
rows

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0

### 2. Extracting multiple rows with same index

In [6]:
df = pd.read_csv('nba.csv' ,index_col='Team')

In [8]:
rows = df.loc["Utah Jazz"]
rows

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Utah Jazz,Trevor Booker,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
Utah Jazz,Trey Burke,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
Utah Jazz,Alec Burks,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
Utah Jazz,Dante Exum,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
Utah Jazz,Derrick Favors,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
Utah Jazz,Rudy Gobert,27.0,C,23.0,7-1,245.0,NaN,1175880.0
Utah Jazz,Gordon Hayward,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
Utah Jazz,Rodney Hood,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
Utah Jazz,Joe Ingles,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
Utah Jazz,Chris Johnson,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
Utah Jazz,Trey Lyles,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
Utah Jazz,Shelvin Mack,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
Utah Jazz,Raul Neto,25.0,PG,24.0,6-1,179.0,NaN,900000.0
Utah Jazz,Tibor Pleiss,21.0,C,26.0,7-3,256.0,NaN,2900000.0
Utah Jazz,Jeff Withey,24.0,C,26.0,7-0,231.0,Kansas,947276.0

### 3. Extracting rows between two index labels

In [9]:
data = pd.read_csv("nba.csv", index_col ="Name")

In [11]:
rows = data.loc['Avery Bradley' : 'Jonas Jerebko']
rows

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

# Extracting rows using Pandas .iloc[] in Python

### 1. Selecting rows using Pandas .iloc

In [7]:
data = pd.read_csv('nba.csv')
row2 = data.iloc[3]
print(row2)

Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: 3, dtype: object

### 2.Selecting Multiple Rows using Pandas .iloc[] in Python

In [9]:
data.iloc[[4,5,6,7,8,9]]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [11]:
data.iloc[4:10]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

### 3.Select Rows by Name or Index usingPandas .iloc[] in Python

In [12]:
data2 = pd.DataFrame({
    'Name': ['Geek1', 'Geek2', 'Geek3', 'Geek4', 'Geek5'],
    'Age': [25, 30, 22, 35, 28],
    'Salary': [50000, 60000, 45000, 70000, 55000]
})

In [13]:
data2.set_index('Name' ,inplace=True)

In [14]:
row_1 = data2.iloc[0,:]
row_1

Age          25
Salary    50000
Name: Geek1, dtype: int64

In [16]:
rows2_to_rows3 = data2.iloc[1:3 ,:]
rows2_to_rows3

       Age  Salary
Name
Geek2   30   60000
Geek3   22   45000