In [1]:
import numpy as np
import pandas as pd

# Indexing and Selecting Data with Pandas
There are basically 3 ways of Indexing and Selecting data in Pandas
- Indexing Data using the [] Operator
- Indexing with .loc[ ]
- Indexing with .iloc[]

## Indexing Data using the [] Operator

### 1. Selecting a Single Column

In [3]:
df = pd.read_csv('nba.csv')
col1 = df['Age']
col1

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ...
453    26.0
454    24.0
455    26.0
456    26.0
457     NaN
Name: Age, Length: 458, dtype: float64

### 2. Selecting Multiple Columns

In [5]:
cols = df[['Age','Name','Salary']]
cols

      Age           Name     Salary
0    25.0  Avery Bradley  7730337.0
1    25.0    Jae Crowder  6796117.0
2    27.0   John Holland        NaN
3    22.0    R.J. Hunter  1148640.0
4    29.0  Jonas Jerebko  5000000.0
..    ...            ...        ...
453  26.0   Shelvin Mack  2433333.0
454  24.0      Raul Neto   900000.0
455  26.0   Tibor Pleiss  2900000.0
456  26.0    Jeff Withey   947276.0
457   NaN            NaN        NaN

[458 rows x 3 columns]

## Indexing with .loc[ ]

### 1. Selecting a Single Row by Label

In [8]:
df1 = pd.read_csv('nba.csv' ,index_col='Name')
print(df1.loc['Avery Bradley'])

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

### 2. Selecting Multiple Rows by Label

In [11]:
rows = df1.loc[["Avery Bradley", "R.J. Hunter"]]
print(rows)

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0

                     College     Salary
Name
Avery Bradley          Texas  7730337.0
R.J. Hunter    Georgia State  1148640.0

### 3. Selecting Specific Rows and Columns

In [12]:
df1

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...
Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sel = df1.loc[["Avery Bradley", "R.J. Hunter"],["Team", "Number", "Position"]]
print(sel)

                         Team  Number Position
Name
Avery Bradley  Boston Celtics     0.0       PG
R.J. Hunter    Boston Celtics    28.0       SG

### 4. Selecting All Rows and Specific Columns

In [17]:
all_rows_specific_columns = df1.loc[:, ["Team", "Position", "Salary"]]
print(all_rows_specific_columns)

                         Team Position     Salary
Name
Avery Bradley  Boston Celtics       PG  7730337.0
Jae Crowder    Boston Celtics       SF  6796117.0
John Holland   Boston Celtics       SG        NaN
R.J. Hunter    Boston Celtics       SG  1148640.0
Jonas Jerebko  Boston Celtics       PF  5000000.0
...                       ...      ...        ...
Shelvin Mack        Utah Jazz       PG  2433333.0
Raul Neto           Utah Jazz       PG   900000.0
Tibor Pleiss        Utah Jazz        C  2900000.0
Jeff Withey         Utah Jazz        C   947276.0
NaN                       NaN      NaN        NaN

[458 rows x 3 columns]

## Indexing with .iloc[]

### 1. Selecting a Single Row by Position

In [19]:
data = pd.read_csv("nba.csv", index_col="Name")
row = data.iloc[3]
print(row)

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

### 2. Selecting Multiple Rows by Position

In [20]:
rows = data.iloc[[3, 5, 7]]
print(rows)

                        Team  Number Position   Age Height  Weight  \
Name
R.J. Hunter   Boston Celtics    28.0       SG  22.0    6-5   185.0
Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0

                    College      Salary
Name
R.J. Hunter   Georgia State   1148640.0
Amir Johnson            NaN  12000000.0
Kelly Olynyk        Gonzaga   2165160.0

### 3. Selecting Specific Rows and Columns by Position

In [21]:
selection = data.iloc[[3, 4], [1, 2]]
print(selection)

               Number Position
Name
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF

### 4. Selecting All Rows and Specific Columns by Position

In [22]:
selection = data.iloc[:, [1, 2]]
print(selection)

               Number Position
Name
Avery Bradley     0.0       PG
Jae Crowder      99.0       SF
John Holland     30.0       SG
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF
...               ...      ...
Shelvin Mack      8.0       PG
Raul Neto        25.0       PG
Tibor Pleiss     21.0        C
Jeff Withey      24.0        C
NaN               NaN      NaN

[458 rows x 2 columns]