In [1]:
import numpy as np
import pandas as pd

## 1. Accessing a DataFrame with a Boolean Index

A Boolean index means the **index labels of the DataFrame are `True` or `False`**.

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Freen", "Becky", "Lingling", "Orm"],
    "Series": ["GAP", "GAP", "The Secret of Us", "The Secret of Us"],
    "Rating": [9.2, 9.5, 9.7, 9.0]
}, index=[True, False, True, False])

print(df)

           Name            Series  Rating
True      Freen               GAP     9.2
False     Becky               GAP     9.5
True   Lingling  The Secret of Us     9.7
False       Orm  The Secret of Us     9.0

In [3]:
df.loc[True]

          Name            Series  Rating
True     Freen               GAP     9.2
True  Lingling  The Secret of Us     9.7

## 2. Applying a Boolean Mask to a DataFrame

A **Boolean mask** is a collection of `True` and `False` values used to filter rows.

- `True` → keep the row
- `False` → remove the row

In [4]:
df = pd.DataFrame({
    "Name": ["Freen", "Becky", "Lingling", "Orm"],
    "Series": ["GAP", "GAP", "The Secret of Us", "The Secret of Us"],
    "Rating": [9.2, 9.5, 9.7, 9.0]
})

print(df)

       Name            Series  Rating
0     Freen               GAP     9.2
1     Becky               GAP     9.5
2  Lingling  The Secret of Us     9.7
3       Orm  The Secret of Us     9.0

In [7]:
mask = df["Rating"] > 9.2

In [8]:
df[mask]

       Name            Series  Rating
1     Becky               GAP     9.5
2  Lingling  The Secret of Us     9.7

In [9]:
df[df["Rating"] > 9.2]

       Name            Series  Rating
1     Becky               GAP     9.5
2  Lingling  The Secret of Us     9.7

# 3. Masking Data Based on Column Value

Column-based masking means **filtering rows based on the values present in a column**.

Pandas checks each value in the column against a condition and produces `True` or `False`.

- `True` → keep the row
- `False` → remove the row

---

## Basic Syntax

```python
df[df["column"] condition]

In [ ]:
# Rating greater than 9
df[df["Rating"] > 9]

       Name            Series  Rating
2  Lingling  The Secret of Us     9.7
3       Orm  The Secret of Us     9.0

In [11]:
# Rating 9.5 or higher
df[df["Rating"] >= 9.5]

       Name            Series  Rating
1     Becky               GAP     9.5
2  Lingling  The Secret of Us     9.7

In [12]:
# Rating less than 9
df[df["Rating"] < 9]

Empty DataFrame
Columns: [Name, Series, Rating]
Index: []

In [13]:
# Rating 9 or lower
df[df["Rating"] <= 9]

  Name            Series  Rating
3  Orm  The Secret of Us     9.0

In [14]:
# Rating exactly 9.5
df[df["Rating"] == 9.5]

    Name Series  Rating
1  Becky    GAP     9.5

In [15]:
# Series is GAP
df[df["Series"] == "GAP"]

    Name Series  Rating
0  Freen    GAP     9.2
1  Becky    GAP     9.5

In [16]:
# Series is NOT GAP
df[df["Series"] != "GAP"]

       Name            Series  Rating
2  Lingling  The Secret of Us     9.7
3       Orm  The Secret of Us     9.0

In [17]:
# GAP AND rating above 9.3
df[(df["Series"] == "GAP") & (df["Rating"] > 9.3)]

    Name Series  Rating
1  Becky    GAP     9.5

In [18]:
# GAP OR 23.5
df[(df["Series"] == "GAP") | (df["Series"] == "23.5")]

    Name Series  Rating
0  Freen    GAP     9.2
1  Becky    GAP     9.5

In [19]:
# NOT GAP
df[~(df["Series"] == "GAP")]

       Name            Series  Rating
2  Lingling  The Secret of Us     9.7
3       Orm  The Secret of Us     9.0

### Most Important Things to Remember

| Symbol / Syntax | Meaning | Example |
|---|---|---|
| `df[condition]` | Filters rows | `df[df["Rating"] > 9]` |
| `==` | Equal to | `df[df["Series"] == "GAP"]` |
| `!=` | Not equal to | `df[df["Series"] != "GAP"]` |
| `>` | Greater than | `df[df["Rating"] > 9]` |
| `<` | Less than | `df[df["Rating"] < 9]` |
| `>=` | Greater than or equal to | `df[df["Rating"] >= 9]` |
| `<=` | Less than or equal to | `df[df["Rating"] <= 9]` |
| `&` | AND — both conditions must be True | `(condition1) & (condition2)` |
| `\|` | OR — at least one condition must be True | `(condition1) \| (condition2)` |
| `~` | NOT — reverses True/False | `~(condition)` |

### Important Rules

- Always put each condition inside `()` when combining conditions.

```python
df[(df["Rating"] > 9) & (df["Series"] == "GAP")]

# 4. Masking Data Based on an Index Value

Index-based masking means **filtering rows based on the values of the DataFrame's index**.

### Basic Syntax

```python
df[df.index condition]

### Comparison Operators

| Operator | Meaning | Example |
|---|---|---|
| `==` | Equal to | `df[df.index == 2]` |
| `!=` | Not equal to | `df[df.index != 2]` |
| `>` | Greater than | `df[df.index > 1]` |
| `<` | Less than | `df[df.index < 2]` |
| `>=` | Greater than or equal to | `df[df.index >= 2]` |
| `<=` | Less than or equal to | `df[df.index <= 1]` |

In [20]:
mask = df.index > 1

In [22]:
df

       Name            Series  Rating
0     Freen               GAP     9.2
1     Becky               GAP     9.5
2  Lingling  The Secret of Us     9.7
3       Orm  The Secret of Us     9.0

In [21]:
df[mask]

       Name            Series  Rating
2  Lingling  The Secret of Us     9.7
3       Orm  The Secret of Us     9.0

In [23]:
df.loc[df.index > 1]

       Name            Series  Rating
2  Lingling  The Secret of Us     9.7
3       Orm  The Secret of Us     9.0